blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/towry/path-git-format/discussions
    about: Ask questions, share ideas, and engage with the community
  - name: Documentation
    url: https://github.com/towry/path-git-format/blob/main/README.md
    about: Read the project documentation and usage examples
