name: Feature Request
description: Suggest a new feature or enhancement for path-git-format
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important Notice

        **This repository is maintained by GitHub Copilot Agent.** Please do not approach the repository owner for coding tasks or implementation details. All code-related work is handled by automated agents.

        Thank you for suggesting a new feature!

        ---

        ### 💝 Support This Project

        If you find path-git-format useful, please consider supporting its development:

        - ⭐ Star this repository
        - 🐦 Share path-git-format with others who might find it useful

        Your support helps keep this project maintained and improved!

  - type: textarea
    id: description
    attributes:
      label: Detailed Feature Description
      description: Provide a clear and detailed description of the feature you'd like to see
      placeholder: |
        What feature would you like to add or improve?
        Why is this feature important?
        What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: How Do You Want It Implemented?
      description: Describe how you envision this feature working
      placeholder: |
        - How should the feature work?
        - What should the user interface look like (CLI arguments, flags, etc.)?
        - What should the output be?
        - Are there any specific technical approaches you'd prefer?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Are There Any Alternative Approaches?
      description: Describe alternative implementations or approaches to solving the same problem
      placeholder: |
        Have you considered any alternative ways to implement this feature?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: |
        Any examples, mockups, or additional information?
    validations:
      required: false
