name: nix ci

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  SPEC_SPLIT_DOTS: 160
  CI_NIX_SHELL: true

jobs:
  release-build:
    strategy:
      matrix:
        os: [macos-latest]
        useDaemon: [false]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          install_url: https://releases.nixos.org/nix/nix-2.9.2/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v14
        if: ${{ success() }}
        with:
          name: towry
          useDaemon: ${{ matrix.useDaemon }}
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Enter env
        run: nix develop
      - name: build
        if: ${{ success() }}
        run: make release && tar -czvf path-git-format.tar.gz -C ./target/release/ path-git-format
      - uses: actions/upload-artifact@v4
        with:
          name: path-git-format.tar.gz
          path: |
            ./path-git-format.tar.gz
          retention-days: 1

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            path-git-*.tar.gz
          generate_release_notes: true
