name: "Rust Test Suite"

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'
      - 'rust-toolchain.toml'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(main): release')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-rustup-stable-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rustup-stable-
            ${{ runner.os }}-rustup-

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          cache: false

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-rust-fmt"
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(main): release')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-rustup-stable-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rustup-stable-
            ${{ runner.os }}-rustup-

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
          cache: false

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-rust-clippy"
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run clippy
        env:
          RUSTFLAGS: -D warnings
        run: cargo clippy --workspace --all-targets --all-features --verbose

  test:
    name: tests (stable)
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore(main): release')"
    needs:
      - fmt
      - clippy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-rustup-stable-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rustup-stable-
            ${{ runner.os }}-rustup-

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-rust-test"
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run tests
        run: cargo test --all-features --verbose

  cross_platform_test:
    name: Cross-platform binary test
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          - os: macos-latest
            target: aarch64-apple-darwin
            toolchain: stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-rustup-${{ matrix.target }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rustup-${{ matrix.target }}-
            ${{ runner.os }}-rustup-

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          cache: false

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1-rust-cross-${{ matrix.target }}"
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build for target
        run: cargo build --release --target ${{ matrix.target }} --verbose

      - name: Test binary functionality
        shell: bash
        run: |
          # Create a comprehensive test
          mkdir -p test_repo && cd test_repo
          git init
          git config user.email "test@example.com"
          git config user.name "Test User"

          # Create initial commit
          echo "test" > file.txt
          git add file.txt
          git commit -m "Initial commit"

          # Test binary with stdin
          printf "/tmp\n\$PWD\n/var" | ../target/${{ matrix.target }}/release/path-git-format --format "{path}: {branch}" || true
          echo "✅ Binary test passed for ${{ matrix.target }}"

      - name: Display binary info
        shell: bash
        run: |
          echo "📊 Binary information for ${{ matrix.target }}:"
          if command -v file >/dev/null 2>&1; then
            file target/${{ matrix.target }}/release/path-git-format
          fi
          ls -lh target/${{ matrix.target }}/release/path-git-format
